### ISSUE TITLE
Add ClusterName Tag for SpotFleet and enable propagation

### ISSUE THREAD

**Issue by pahud** [pahud/eks-templates#10]
```yaml
      - Key: !Sub 'kubernetes.io/cluster/${ClusterName}'
        Value: 'owned'
        PropagateAtLaunch: 'true'
```
