### ISSUE TITLE
support different cluster version

### ISSUE THREAD

**Issue by pahud** [pahud/eks-templates#46]
support different cluster version in parameter

```
  ClusterVersion:
    Description: Cluster Version
    Type: String
    Default: "latest"
    AllowedValues:
      - 1.10
      - 1.11
      - 1.12
      - latest
```
