### ISSUE TITLE
Support NodeVolumeSize in cloudformation/nodegroup.yaml

### ISSUE THREAD

**Issue by knaoe** [pahud/eks-templates#56]
Currently, there is no configuration about EBS storage in the LauchTemplate. So, the default size, 20GiB, will be assigned to nodes. It looks too small for heavy workloads. It would be great if you add NodeVolumeSize parameter to configure the size like this.

```yaml
MyLaunchTemplate:
  Properties:
    LaunchTemplateData: 
       BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: !Ref NodeVolumeSize
              VolumeType: gp2
              DeleteOnTermination: true
```
